#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["AutenticacionService.Api/AutenticacionService.Api.csproj", "AutenticacionService.Api/"]
COPY ["AutenticacionService.Business/AutenticacionService.Business.csproj", "AutenticacionService.Business/"]
COPY ["AutenticacionService.Persistence/AutenticacionService.Persistence.csproj", "AutenticacionService.Persistence/"]
COPY ["AutenticacionService.Domain/AutenticacionService.Domain.csproj", "AutenticacionService.Domain/"]
RUN dotnet restore "AutenticacionService.Api/AutenticacionService.Api.csproj"
COPY . .
WORKDIR "/src/AutenticacionService.Api"
RUN dotnet build "AutenticacionService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AutenticacionService.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
ENTRYPOINT ["dotnet", "AutenticacionService.Api.dll"]